name: Deploy Angular app to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=6144
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: front

      - name: Build
        run: npm run git-build
        working-directory: front

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          path: docs
